on:
  push:
    branches:
      # main브랜치에 push될 때 아래 workflow를 실행해줘
      - main
# 하나의 workflow는 1개 이상의 job이 올 수 있다.
jobs:
  My-Job:
    #Github Actions를 실행할 서버 종류 선택
    runs-on: ubuntu-latest
    # step: 특정한 작업을 수행하는 단위
    # job은 여러개의 step으로 구성됨.
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: 여러 문장 작성하기
        run: |
          echo "Have"
          echo "a "
          echo "Good Time"
      - name: 변수 사용이 가능하다.
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: 사용자 변수 사용 가능하다.
        run: |
          echo ${{ secrets.MEM_ID}}
          echo ${{ secrets.MEM_PW}}
